(GEN-4410) Prometheus http
gener8ads/lib-go pull request #23
Opened 2021-12-22 14:05 UTC by DuncanGener8

2022-01-06 09:27 UTC, nmec requested changes

2022-01-06 09:27 UTC, nmec commented on pkg/prometheus/http.go
> +		elapsed := float64(time.Since(start)) / float64(time.Second)
Prom has helpers for timing:

```go
// replaces start = now
timer := prometheus.NewTimer(requestDuration)

// ...do stuff that takes time..

// replaces elapsed calculation
timer.ObserveDuration()
```

2022-01-06 09:44 UTC, DuncanGener8 commented on pkg/prometheus/http.go
> +		elapsed := float64(time.Since(start)) / float64(time.Second)
The issue with this approach (IIRC this came up last time, when I implemented this directly into the AuthAPI)
- Is that the observer itself only gets configured after the underlying method has executed. This happens, because I'm labelling the request with the resulting Status (we don't necessarily want to mix response Times for 429s with 200s, for example).

2022-01-07 11:07 UTC, nmec commented on pkg/prometheus/http.go
> +		elapsed := float64(time.Since(start)) / float64(time.Second)
Fair enough, in that case, let's take a cue from how that method works internally and we can omit the division + casting like so:

```go
elapsed := time.Since(start)
requestDuration.Observe(elapsed.Seconds())
```

The `elapsed` should be captured immediately after `c.Next()` for accuracy.

2022-01-14 10:42 UTC, nmec approved these changes

2022-01-14 14:43 UTC, merged